### ISSUE TITLE
how to remove Authentication Users

### ISSUE THREAD

**Issue by rambozzang** [insideapp-srl/flutter_supabase_chat_core#10]
Supabase.instance.client.auth.admin.deleteUser is not working 

 AuthException(message: User not allowed, statusCode: 403)

plz help me

**Comment by rickypid** [comment]
Hi @rambozzang ,

If you are using `Supabase.instance.client.auth.admin.deleteUser` on a client it is not allowed as you can only do this with a service key. This functionality is normally backend.
