### ISSUE TITLE
When will v2 be released?

### ISSUE THREAD

**Issue by rambozzang** [insideapp-srl/flutter_supabase_chat_core#6]
When will v2 be released?

I'm waiting.
Now the time is approaching when I need to deploy the place into production, and I need confirmation.

**Comment by rickypid** [comment]
hi @rambozzang,

What do you expect? I have two PRs to merge but at the moment I have not implemented any new features. With the closing of the two PRs I will release version 1.0.0.

Let me have feedback

**Comment by rambozzang** [comment]
1. leave the room alone
2. Invite others to the room
3. display the total number of unread messages in the room list
4. indicate whether the room is a multi-person chat room or not

Please and thank you

**Comment by rickypid** [comment]
But are you referring to the example project or would you be implementing the methods in the package?
