### ISSUE TITLE
Wrong min Dart SDK version for Flutter 3.22.x support

### ISSUE THREAD

**Issue by Parfyonator** [insideapp-srl/flutter_supabase_chat_core#9]
Hi. Thanks for this analog of `flutter_firebase_chat_core` for Supabase.

I noticed a small issue in the last commit for Flutter 3.22.x. The actual Dart SDK for 3.22.0 release is 3.4.0. So it should be changed from 3.4.1 to 3.4.0. It may not seem like much but it may result in `flutter pub get` fail for those who use Flutter 3.22.0 in their project.

<img width="880" alt="image" src="https://github.com/user-attachments/assets/6f8ce72d-de66-4567-9c66-e5142a1b5d84">

**Comment by rickypid** [comment]
Thanks @Parfyonator, I'll see if I can fix it in the next release. 👍
